export const getDefaultTemplate = () => [
  {
    id: "main-image",
    elementType: "image",
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/text-editor-q4PVzyjDcuig9i4hLmgvReaMzJ8hhm.png",
    alt: "Decorative image",
    width: "50",
    height: "100",
    borderRadius: "0",
    position: "left",
    opacity: "100",
  },
  {
    id: "heading",
    elementType: "text",
    content: "Unleash your genius",
    fontFamily: "Georgia",
    fontWeight: "400",
    fontSize: "48",
    fontColor: "#494D3E",
    lineHeight: "1.2",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "description",
    elementType: "text",
    content: "Wondering how to take your creative talent and turn it into a scalable business? You're in good hands, friend. Sign up below to receive my 100% free step-by-step guide on how to launch and grow a creative business that celebrates your genius.",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "field-1",
    elementType: "field",
    type: "text",
    placeholder: "FIRST NAME",
    label: "FIRST NAME",
    required: false,
    fillColor: "transparent",
    borderColor: "#1F2937",
    borderWidth: "2",
    borderRadius: "999",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "field-2",
    elementType: "field",
    type: "email",
    placeholder: "EMAIL ADDRESS",
    label: "EMAIL ADDRESS",
    required: false,
    fillColor: "transparent",
    borderColor: "#1F2937",
    borderWidth: "2",
    borderRadius: "999",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "download-button",
    elementType: "button",
    label: "DOWNLOAD",
    fillColor: "#494D3E",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "999",
    height: "48",
    width: "100",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "14",
    fontColor: "#FFFFFF",
    lineHeight: "1",
    letterSpacing: "1",
    textAlign: "center",
  },
]

export const getBlankTemplate = () => [
  {
    id: "heading",
    elementType: "text",
    content: "Your heading here",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "32",
    fontColor: "#000000",
    lineHeight: "1.2",
    letterSpacing: "0",
    textAlign: "left",
  },
]

export const getTemplate2 = () => [
  {
    id: "main-image",
    elementType: "image",
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dried-flowers-beige-background-elegant-minimalist-photo-Y2mH8kX9jKL5pQrN3sT6uW4vZaBcDe.jpg",
    alt: "Dried flowers on beige background",
    width: "50",
    height: "100",
    borderRadius: "0",
    position: "left",
    opacity: "100",
  },
  {
    id: "heading",
    elementType: "text",
    content: "Unleash\nyour creativity",
    fontFamily: "Georgia",
    fontWeight: "400",
    fontSize: "56",
    fontColor: "#FFFFFF",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "description",
    elementType: "text",
    content: "Wondering how to take your creative talent and turn it into a sustainable business? You're in good hands, friend. Sign up below to receive my 100% free step-by-step guide on how to launch and grow a creative business that celebrates your genius.",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#D1D5DB",
    lineHeight: "1.6",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "field-1",
    elementType: "field",
    type: "text",
    placeholder: "FIRST NAME",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#FFFFFF",
    borderWidth: "2",
    borderRadius: "8",
    height: "52",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "13",
    fontColor: "#FFFFFF",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "left",
  },
  {
    id: "field-2",
    elementType: "field",
    type: "email",
    placeholder: "EMAIL ADDRESS",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#FFFFFF",
    borderWidth: "2",
    borderRadius: "8",
    height: "52",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "13",
    fontColor: "#FFFFFF",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "left",
  },
  {
    id: "download-button",
    elementType: "button",
    label: "DOWNLOAD",
    fillColor: "#E5E7EB",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "8",
    height: "52",
    width: "60",
    fontFamily: "Arial",
    fontWeight: "600",
    fontSize: "13",
    fontColor: "#374151",
    lineHeight: "1",
    letterSpacing: "1",
    textAlign: "center",
  },
]

export const getTemplate3 = () => [
  {
    id: "heading",
    elementType: "text",
    content: "Take10% off\nyour first order",
    fontFamily: "Georgia",
    fontWeight: "700",
    fontSize: "64",
    fontColor: "#1F2937",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "center",
  },
  {
    id: "main-image",
    elementType: "image",
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fashion-model-beige-outfit-bucket-hat-casual-style-minimalist-photo-XyZ9aB1cD2eF3gH4iJ5kL6mN7oP8qR.jpg",
    alt: "Fashion model in casual beige outfit",
    width: "40",
    height: "80",
    borderRadius: "0",
    position: "inline",
    opacity: "100",
  },
  {
    id: "email-field",
    elementType: "field",
    type: "email",
    placeholder: "EMAIL ADRESS",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#1F2937",
    borderWidth: "1",
    borderRadius: "0",
    height: "56",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "13",
    fontColor: "#9CA3AF",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "center",
  },
  {
    id: "submit-button",
    elementType: "button",
    label: "GET 10% OFF",
    fillColor: "#3D2817",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "0",
    height: "56",
    width: "100",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "14",
    fontColor: "#FFFFFF",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "center",
  },
]

export const getTemplate4 = () => [
  {
    id: "heading",
    elementType: "text",
    content: "Help us\nimprove!",
    fontFamily: "Arial",
    fontWeight: "700",
    fontSize: "72",
    fontColor: "#000000",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "center",
  },
  {
    id: "description",
    elementType: "text",
    content: "Your opinion is very important to us. Please answer this quick survey and help us provide an even better service.",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#4B5563",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "center",
  },
  {
    id: "question-1-label",
    elementType: "text",
    content: "1. How would you rate your overall experience with us?",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#000000",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "rating-field",
    elementType: "field",
    type: "rating",
    placeholder: "",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "0",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#000000",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
    maxRating: 5,
    starColor: "#000000",
  },
  {
    id: "question-2-label",
    elementType: "text",
    content: "2. How would you rate your overall experience with us?",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#000000",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "opinion-field",
    elementType: "field",
    type: "long-text",
    placeholder: "Write your opinion here.",
    label: "",
    required: false,
    fillColor: "#FFFFFF",
    borderColor: "#D1D5DB",
    borderWidth: "1",
    borderRadius: "4",
    height: "120",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
    rows: 5,
  },
  {
    id: "question-3-label",
    elementType: "text",
    content: "3. What can we improve?",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#000000",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "suggestions-field",
    elementType: "field",
    type: "long-text",
    placeholder: "Write suggestions or criticisms.",
    label: "",
    required: false,
    fillColor: "#FFFFFF",
    borderColor: "#D1D5DB",
    borderWidth: "1",
    borderRadius: "4",
    height: "120",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
    rows: 5,
  },
  {
    id: "question-4-label",
    elementType: "text",
    content: "4. Would you recommend our company to friends or colleagues?",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#000000",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "recommend-field",
    elementType: "field",
    type: "multiple-choice",
    placeholder: "",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "0",
    height: "32",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#000000",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
    multipleChoiceType: "radio",
    options: ["for sure", "maybe", "probably not"],
  },
  {
    id: "submit-button",
    elementType: "button",
    label: "Send Reply",
    fillColor: "#000000",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "4",
    height: "56",
    width: "100",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "16",
    fontColor: "#FFFFFF",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "center",
  },
]

export const getTemplate5 = () => [
  {
    id: "heading",
    elementType: "text",
    content: "Schedule your\nappointment.",
    fontFamily: "Arial",
    fontWeight: "700",
    fontSize: "56",
    fontColor: "#1F2937",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "description",
    elementType: "text",
    content: "Please fill out the form below to request an appointment. We will contact you to confirm the time.",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "15",
    fontColor: "#4B5563",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "name-label",
    elementType: "text",
    content: "Name",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "name-field",
    elementType: "field",
    type: "text",
    placeholder: "Type your full name",
    label: "",
    required: false,
    fillColor: "#FFFFFF",
    borderColor: "#9CA3AF",
    borderWidth: "1",
    borderRadius: "8",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "email-label",
    elementType: "text",
    content: "Email",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "email-field",
    elementType: "field",
    type: "email",
    placeholder: "",
    label: "",
    required: false,
    fillColor: "#FFFFFF",
    borderColor: "#9CA3AF",
    borderWidth: "1",
    borderRadius: "8",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "phone-label",
    elementType: "text",
    content: "Phone",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "phone-field",
    elementType: "field",
    type: "text",
    placeholder: "(__) ___-___",
    label: "",
    required: false,
    fillColor: "#FFFFFF",
    borderColor: "#9CA3AF",
    borderWidth: "1",
    borderRadius: "8",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "date-label",
    elementType: "text",
    content: "Date",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "date-field",
    elementType: "field",
    type: "text",
    placeholder: "25/03/2025",
    label: "",
    required: false,
    fillColor: "#FFFFFF",
    borderColor: "#9CA3AF",
    borderWidth: "1",
    borderRadius: "8",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "hour-label",
    elementType: "text",
    content: "Hour",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "hour-field",
    elementType: "field",
    type: "text",
    placeholder: "12:00 p.m",
    label: "",
    required: false,
    fillColor: "#FFFFFF",
    borderColor: "#9CA3AF",
    borderWidth: "1",
    borderRadius: "8",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "message-label",
    elementType: "text",
    content: "Message",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "message-field",
    elementType: "field",
    type: "long-text",
    placeholder: "Please provide any important information about your case here.",
    label: "",
    required: false,
    fillColor: "#FFFFFF",
    borderColor: "#9CA3AF",
    borderWidth: "1",
    borderRadius: "8",
    height: "120",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#6B7280",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
    rows: 5,
  },
  {
    id: "submit-button",
    elementType: "button",
    label: "Request an Appointment",
    fillColor: "#3D3D3D",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "8",
    height: "56",
    width: "60",
    fontFamily: "Arial",
    fontWeight: "500",
    fontSize: "15",
    fontColor: "#FFFFFF",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "center",
  },
]

export const getTemplate6 = () => [
  {
    id: "heading",
    elementType: "text",
    content: "Download the\nchecklist",
    fontFamily: "Georgia",
    fontWeight: "400",
    fontSize: "72",
    fontColor: "#1F2937",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "center",
  },
  {
    id: "description",
    elementType: "text",
    content: "Looking for guidance to help your launch become a huge success? Look no further—my launch checklist will hold your hand through it all. Subscribe below to get instant access to my free download and insiders-only weekly content.",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#6B7280",
    lineHeight: "1.6",
    letterSpacing: "0",
    textAlign: "center",
  },
  {
    id: "first-name-field",
    elementType: "field",
    type: "text",
    placeholder: "FIRST NAME",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#4B5563",
    borderWidth: "1",
    borderRadius: "4",
    height: "56",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "13",
    fontColor: "#6B7280",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "left",
  },
  {
    id: "last-name-field",
    elementType: "field",
    type: "text",
    placeholder: "LAST NAME",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#4B5563",
    borderWidth: "1",
    borderRadius: "4",
    height: "56",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "13",
    fontColor: "#6B7280",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "left",
  },
  {
    id: "email-field",
    elementType: "field",
    type: "email",
    placeholder: "EMAIL ADDRESS",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#4B5563",
    borderWidth: "1",
    borderRadius: "4",
    height: "56",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "13",
    fontColor: "#6B7280",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "left",
  },
  {
    id: "interests-label",
    elementType: "text",
    content: "What would you like to hear about?",
    fontFamily: "Georgia",
    fontWeight: "400",
    fontSize: "18",
    fontColor: "#1F2937",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "interests-field",
    elementType: "field",
    type: "multiple-choice",
    placeholder: "",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "0",
    height: "32",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#1F2937",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
    multipleChoiceType: "checkbox",
    options: ["Insider news", "Business tips", "Special offers", "In-person events"],
  },
  {
    id: "submit-button",
    elementType: "button",
    label: "DOWNLOAD",
    fillColor: "#F5F5F0",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "4",
    height: "56",
    width: "50",
    fontFamily: "Arial",
    fontWeight: "600",
    fontSize: "14",
    fontColor: "#1F2937",
    lineHeight: "1",
    letterSpacing: "1",
    textAlign: "center",
  },
]

export const getTemplate7 = () => [
  {
    id: "heading",
    elementType: "text",
    content: "How much did you\nlike this product?",
    fontFamily: "Arial",
    fontWeight: "700",
    fontSize: "64",
    fontColor: "#FFFFFF",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "center",
  },
  {
    id: "description",
    elementType: "text",
    content: "Your feedback will help us throw an even better party next year—and it'll only take a minute.",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#E9D5FF",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "center",
  },
  {
    id: "product-image",
    elementType: "image",
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/product-tube-cosmetic-white-purple-branding-mockup-XyZ9aB1cD2eF3gH4iJ5kL6mN7oP8qR.png",
    alt: "Product image",
    width: "30",
    height: "60",
    borderRadius: "0",
    position: "inline",
    opacity: "100",
  },
  {
    id: "name-question",
    elementType: "text",
    content: "First up, what's your name?",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#FFFFFF",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "name-field",
    elementType: "field",
    type: "text",
    placeholder: "NAME",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#FFFFFF",
    borderWidth: "1",
    borderRadius: "4",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#E9D5FF",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "left",
  },
  {
    id: "email-question",
    elementType: "text",
    content: "What's your email?",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#FFFFFF",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "email-field",
    elementType: "field",
    type: "email",
    placeholder: "EMAIL ADDRESS",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#FFFFFF",
    borderWidth: "1",
    borderRadius: "4",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#E9D5FF",
    lineHeight: "1",
    letterSpacing: "0.5",
    textAlign: "left",
  },
  {
    id: "details-question",
    elementType: "text",
    content: "Let's get into the details...",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#FFFFFF",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "details-field",
    elementType: "field",
    type: "long-text",
    placeholder: "ANYTHING ELSE YOU'D LIKE TO SHARE?",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "#FFFFFF",
    borderWidth: "1",
    borderRadius: "4",
    height: "100",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#E9D5FF",
    lineHeight: "1.5",
    letterSpacing: "0.5",
    textAlign: "left",
    rows: 4,
  },
  {
    id: "rating-question",
    elementType: "text",
    content: "Overall, how would you rate the event?",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "16",
    fontColor: "#FFFFFF",
    lineHeight: "1.5",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "rating-field",
    elementType: "field",
    type: "rating",
    placeholder: "",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "0",
    height: "48",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#FFFFFF",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
    maxRating: 5,
    starColor: "#FFFFFF",
  },
  {
    id: "submit-button",
    elementType: "button",
    label: "DOWNLOAD",
    fillColor: "#FFFFFF",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "4",
    height: "52",
    width: "40",
    fontFamily: "Arial",
    fontWeight: "600",
    fontSize: "14",
    fontColor: "#7C3AED",
    lineHeight: "1",
    letterSpacing: "1",
    textAlign: "center",
  },
]

export const getTemplate8 = () => [
  {
    id: "product-image",
    elementType: "image",
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/product-tube-cosmetic-white-purple-branding-mockup-XyZ9aB1cD2eF3gH4iJ5kL6mN7oP8qR.png",
    alt: "Product image",
    width: "50",
    height: "100",
    borderRadius: "0",
    position: "right",
    opacity: "100",
  },
  {
    id: "heading",
    elementType: "text",
    content: "How would you\nrate the quality\nof this product?",
    fontFamily: "Arial",
    fontWeight: "700",
    fontSize: "72",
    fontColor: "#FFFFFF",
    lineHeight: "1.1",
    letterSpacing: "0",
    textAlign: "left",
  },
  {
    id: "rating-field",
    elementType: "field",
    type: "rating",
    placeholder: "",
    label: "",
    required: false,
    fillColor: "transparent",
    borderColor: "transparent",
    borderWidth: "0",
    borderRadius: "0",
    height: "64",
    fontFamily: "Arial",
    fontWeight: "400",
    fontSize: "14",
    fontColor: "#FFFFFF",
    lineHeight: "1",
    letterSpacing: "0",
    textAlign: "left",
    maxRating: 5,
    starColor: "#FFFFFF",
  },
]

export const getDefaultBackground = (template?: string) => {
  if (template === 'template-2') {
    return {
      type: "color" as const,
      color: "#5A6152",
      gradientFrom: "#5A6152",
      gradientTo: "#4A5042",
      gradientDirection: "to bottom" as const,
      imageUrl: "",
      imageOpacity: "100",
    }
  }

  if (template === 'template-3') {
    return {
      type: "color" as const,
      color: "#E5E1D8",
      gradientFrom: "#E5E1D8",
      gradientTo: "#D4CFC8",
      gradientDirection: "to bottom" as const,
      imageUrl: "",
      imageOpacity: "100",
    }
  }

  if (template === 'template-4') {
    return {
      type: "color" as const,
      color: "#F5F5F0",
      gradientFrom: "#F5F5F0",
      gradientTo: "#EEEEE8",
      gradientDirection: "to bottom" as const,
      imageUrl: "",
      imageOpacity: "100",
    }
  }

  if (template === 'template-5') {
    return {
      type: "color" as const,
      color: "#E8E5DF",
      gradientFrom: "#E8E5DF",
      gradientTo: "#DDD9D3",
      gradientDirection: "to bottom" as const,
      imageUrl: "",
      imageOpacity: "100",
    }
  }

  if (template === 'template-6') {
    return {
      type: "color" as const,
      color: "#D9D5CC",
      gradientFrom: "#D9D5CC",
      gradientTo: "#CCC8BF",
      gradientDirection: "to bottom" as const,
      imageUrl: "",
      imageOpacity: "100",
    }
  }

  if (template === 'template-7') {
    return {
      type: "color" as const,
      color: "#7C3AED",
      gradientFrom: "#7C3AED",
      gradientTo: "#6D28D9",
      gradientDirection: "to bottom" as const,
      imageUrl: "",
      imageOpacity: "100",
    }
  }

  if (template === 'template-8') {
    return {
      type: "color" as const,
      color: "#7C3AED",
      gradientFrom: "#7C3AED",
      gradientTo: "#6D28D9",
      gradientDirection: "to bottom" as const,
      imageUrl: "",
      imageOpacity: "100",
    }
  }

  return {
    type: "color" as const,
    color: "#EDE8E3",
    gradientFrom: "#EDE8E3",
    gradientTo: "#D4CFC8",
    gradientDirection: "to bottom" as const,
    imageUrl: "",
    imageOpacity: "100",
  }
}
